### ISSUE TITLE
FetchError: network timeout at: https://onfleet.com/api/v2/tasks/batch

### ISSUE THREAD

**Issue by calvinturbo** [onfleet/node-onfleet#16]
When creating 100 tasks (or more) via batchCreate, only around 92 show up in OnFleet and Firestore Console shows a timeout error. I think timeout setting should be changed to make sure the 500 task limit can be reached without getting a timeout error.

> Unhandled error { FetchError: network timeout at: https://onfleet.com/api/v2/tasks/batch
>     at Timeout.<anonymous> (/srv/node_modules/node-fetch/lib/index.js:1448:13)
>     at ontimeout (timers.js:498:11)
>     at tryOnTimeout (timers.js:323:5)
>     at Timer.listOnTimeout (timers.js:290:5)
>   message: 'network timeout at: https://onfleet.com/api/v2/tasks/batch',
>   type: 'request-timeout' }

**Comment by jamesliupenn** [comment]
Hi @calvinturbo, thanks for reaching out. Note that the timeout is a set time threshold and not by amount of tasks, so we cannot guarantee how many tasks will go through before the timeout hits.

I have reviewed your PR and provided comments for the next steps. For `tasks/batch` endpoint, it will likely still timeout if you have too many tasks to batchCreate from our experience. In cases like that, we suggest grouping tasks into 200~300 a group or to bypass geocoding if you have coordinates available to expedite the task creation process.

Once https://github.com/onfleet/node-onfleet/pull/17 is fixed, you should be able to proceed to processing more tasks within the timeout limit.
