### ISSUE TITLE
[BUG] No reservoir updates due to 0 x-ratelimit-remaining on dynamic Rate Limiter

### ISSUE THREAD

**Issue by ssalaam** [onfleet/node-onfleet#19]
After 1 or 2 errors returned from a create Task or create Destination request i.e., all API requests then start to stall/timeout. The only thing that fixes this is restarting my node server. 

At first I thought it had to do with rate limiting but then I read that this library auto enforces the limit.

Has anyone experienced a similar issue?

**Comment by jamesliupenn** [comment]
Hi @ssalaam I have not heard of such problems so far. Would you be able to tell me the organization that you are working for so I can look up your requests and possibly timeout causes? Thanks for reporting!

**Comment by jtassin** [comment]
I had the same problem recently.
It appeared to be a side effect of the new rateLimiter.

Here : 
https://github.com/onfleet/node-onfleet/blob/master/lib/Methods.js#L103

```js
reassignRate(res.headers.get('x-ratelimit-remaining'));
```

I got cases where the reservoir is set to 0 and all following requests are stucks.

One solution could be to set a minimum to the reservoir or authorize to disable the reassigner.

I had to donwgrade to the previous onfleet client to solve my problem.

**Comment by jamesliupenn** [comment]
@jtassin great catch, I've submitted a PR to add in a basic safeguard against `x-ratelimit-remaining` returning `0`: https://github.com/onfleet/node-onfleet/pull/21

Let me know if this is sufficient to fix your current problems :)

**Comment by jtassin** [comment]
> @jtassin great catch, I've submitted a PR to add in a basic safeguard against `x-ratelimit-remaining` returning `0`: #21
> 
> Let me know if this is sufficient to fix your current problems :)

Great, thx
It seems good to me, it should definitely avoid stuck instances.

Don't you think that we should also invoke `reassignRate` in case of errors ?

Especially error 2300 here : https://github.com/onfleet/node-onfleet/pull/21/files#diff-ab473327da75fd9892d136d5f1565f4bL117

**Comment by jtassin** [comment]
> @jtassin - in cases of 2300 errors, they are triggered when the `x-ratelimit-remaining` hits 0.

Yep, but for me, this error imply to reduce the reservoir size.

The new commit sounds good to me 👍

**Comment by ssalaam** [comment]
Thank you for the timely responses! 
Should I downgrade the version or is it likely the PR will be merged soon?
Excuse my urgency. It seems like the issue we are running into is slowing down a crucial business process.

**Comment by jamesliupenn** [comment]
@ssalaam this will be merged today!

**Comment by jamesliupenn** [comment]
@ssalaam this fix is now released: https://www.npmjs.com/package/@onfleet/node-onfleet in v1.1.0

**Comment by ssalaam** [comment]
thank you!!
