### ISSUE TITLE
[BUG] Can't able to pass time inside `from` query

### ISSUE THREAD

**Issue by eashish93** [onfleet/node-onfleet#20]
**Describe the bug**

I want to get all the tasks by timestamp, but can't be able to do it neither with this package or with any other request lib (fetch, axios etc..)

**To Reproduce**
1. Run this code 
```js
const date = Date.now();
const onfleet = new OnFleet(ONFLEET_API_KEY);

onfleet.tasks.get({from: date})
.then(console.log)
.catch(console.error);
```
2. Error response I'm getting 
```js
{
    code: 'InvalidContent',
    message: {
      error: 1000,
      message: 'The values of one or more parameters are invalid.',
      cause: 'From time was not provided or contains an invalid value',
      request: '825fb77b-66f3-4cc1-8192-0ac4c0898239',
      remoteAddress: '<ip>'
  }
}

```
However, if you replace `date` variable with constant value like  `1591086202458`, then it's working.

**Comment by marcobeltempo** [comment]
@eashish93 you need to call `new` on the date object.

```
typeof Date().valueOf() === 'string'
typeof new Date().valueOf() === 'number'
```

**Comment by eashish93** [comment]
@marcobeltempo, it's a problem in firestore emulator btw. It was working on production. Also, I'm using `Date.now()` which gives numerical value.
