### ISSUE TITLE
[BUG] Requests not rate limited

### ISSUE THREAD

**Issue by wginsberg** [onfleet/node-onfleet#23]
**Describe the bug**
Making too many calls e.g. with `tasks.get(<shortId>, 'shortId')` results in `RateLimitError`, instead of limiting the request rate and avoiding the api error.

**To Reproduce**
Make > 20 requests

```
const Onfleet = require('@onfleet/node-onfleet')
const onfleet = new Onfleet(process.env.ONFLEET_API_KEY)

const getStore = n => onfleet.tasks.get('f67c39c4', 'shortId')
    .then(response => console.log(n, response.destination.address.name))

Array.from({ length: 25 }).map((_, i) => getStore(i))
```

**Expected behavior**
```
0 'store name'
1 'store name'
2 'store name'
...
23 'store name'
24 'store name'
```

**Actual behavior**
```
2 'destination name'
0 'destination name'
3 'destination name'
...
17 'destination name'
18 'destination name'
(node:31257) UnhandledPromiseRejectionWarning: RateLimitError: You have exceeded our per-second request limit. Please slow down.
    at res.json.then (/.../@onfleet/node-onfleet/lib/Methods.js:120:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:31257) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:31257) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:31257) UnhandledPromiseRejectionWarning: RateLimitError: You have exceeded our per-second request limit. Please slow down.
    at res.json.then (/.../@onfleet/node-onfleet/lib/Methods.js:120:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:31257) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
21 'destination name'
22 'destination name'
23 'destination name'
24 'destination name'
```

**Additional context**
"@onfleet/node-onfleet": "1.1.0"

**Comment by wginsberg** [comment]
@jamesliupenn thanks for the response!

This was an issue for us when setting up our automated tests and we were hitting the api a ton in a short amount of time.
For now we're bypassing this package to hit the api only when necessary, so rate limiting is not a problem for the time being.

On a side note, I wonder if these constants and others in this package could be made configurable instead? e.g.
```
new Onfleet({
    LIMITER_MIN_TIME: <something else>,
    DEFAULT_URL: '<a mock server>'
})
```

**Comment by wginsberg** [comment]
@jamesliupenn as we've been again experiencing temporary bans, the #25 change looks really promising

**Comment by jamesliupenn** [comment]
> @jamesliupenn thanks for the response!
> 
> This was an issue for us when setting up our automated tests and we were hitting the api a ton in a short amount of time.
> For now we're bypassing this package to hit the api only when necessary, so rate limiting is not a problem for the time being.
> 
> On a side note, I wonder if these constants and others in this package could be made configurable instead? e.g.
> 
> ```
> new Onfleet({
>     LIMITER_MIN_TIME: <something else>,
>     DEFAULT_URL: '<a mock server>'
> })
> ```

Hi Will, we intend to keep these constants in sync with our API constraints, so making it configurable per user would not be considered.

**Comment by jamesliupenn** [comment]
> @jamesliupenn as we've been again experiencing temporary bans, the #25 change looks really promising

I will merge this and publish a new version of the node-onfleet library today.

**Comment by jamesliupenn** [comment]
Closing this for now as bugfix was merged

**Comment by jamesliupenn** [comment]
@wginsberg https://www.npmjs.com/package/@onfleet/node-onfleet v1.1.1 has been published
