### ISSUE TITLE
[BUG] Issue with the rate limiter reassignRate, jobs get stuck in the job queue forever

### ISSUE THREAD

**Issue by fahadbraveknight** [onfleet/node-onfleet#28]
**Description**

There is an issue with the reservoir updating process. The `reservoir` is not updated even after `reassignRate` is called to update the `reservoirRefreshAmount`, which ideally should update the `reservoir` after the `reservoirRefreshInterval`, after making api call. 

Gradually the `reservoir` gets depleted, i.e. becomes 0. Since the `reservoir` is 0 and is not being refreshed, no job is picked up for execution and is kept in job queue forever. This in turns keeps the main process hanging with no timeout or exception being thrown.

**To Reproduce**

Steps to reproduce the behaviour:
1. Call the onfleet resources using multiple instance or same instance
2. After making 20 calls any you will stop receiving data from the instance method, if you are using async/await, the main threads then hangs forever.

**Expected behavior**

Expected data within desirable time limits when jobs are not throttled/rate limited.

**Screenshots**

![image](https://user-images.githubusercontent.com/13063576/101768305-6891d980-3b0b-11eb-8da2-34b964137c63.png)

You can see below the queue count has reached 800 and `reservoir` is still 0

**Solution**

Instead of updating the `reservoirRefreshAmount` which is expected to refresh the `reservoir` after the `reservoirRefreshInterval`, you can set a default `reservoir` value as 3 and whenever the reservoir's `depleted` event is triggered, you can make a test api call to get the latest rate limiting headers and use it to update the `reservoir`.

Also the limiter instance is shared across the entire library. If there is a use case wherein i instantiate my library for different apiKeys of different organisation, the limiter instance will be shared across all apiKey instances, much likely to cause an anomaly in the job execution.

**Additional context**

PFB link as reference for a proper exhaustion strategy:
https://github.com/SGrondin/bottleneck/issues/51

**Comment by jamesliupenn** [comment]
@fahadbraveknight thanks for bringing this to our attention, we'll be taking a look at it soon!

**Comment by jamesjjk** [comment]
@jamesliupenn Is there a work around for this, we found this to be a serious problem too. And unworkable in production.

**Comment by jamesliupenn** [comment]
> @jamesliupenn Is there a work around for this, we found this to be a serious problem too. And unworkable in production.

Hi there, reverting the version of the package back to before rate limiting was introduced is my best suggestion now if it impacts your production.

We'll be sure to take a look this upcoming week, thanks for reporting!

**Comment by jamesjjk** [comment]
@jamesliupenn Can you confirm its version 1.0.5

**Comment by jamesliupenn** [comment]
@jamesjjk yes it is v1.0.5

**Comment by jamesliupenn** [comment]
@fahadbraveknight @jamesjjk 

**Reservoir Depletion**
> Instead of updating the reservoirRefreshAmount which is expected to refresh the reservoir after the reservoirRefreshInterval, you can set a default reservoir value as 3 and whenever the reservoir's depleted event is triggered, you can make a test api call to get the latest rate limiting headers and use it to update the reservoir.

I agree that this has been a bit wonky as the `reservoirRefreshAmount` didn't really refresh upon `reassignRate`. I consistently get the same `reservoir` when I called the following in the library right after `reassignRate`:

```
    limiter.currentReservoir()
      .then((reservoir) => {
        console.log(`Current Reservoir: ${reservoir}`);
      });
```
I will make the changes to `reassignRate` to update the `reservoir` directly instead and drop `reservoirRefreshInterval`. I hope this would resolve the issue as described. If any of you can provide me with a test sample to replicate the issue that you see, I can run it against the new changes and see if that fixes the problem.

**Anomaly in Reservoir**
> Also the limiter instance is shared across the entire library. If there is a use case wherein i instantiate my library for different apiKeys of different organisation, the limiter instance will be shared across all apiKey instances, much likely to cause an anomaly in the job execution.

If you were to perform API actions on a different organization, you are creating a new instance by calling `new Onfleet(<api_key>` and reservoirs are not shared. I've performed a test where I am constantly accessing the API with one organization via an infinite loop in `Script1` (I purposely controlled `x-ratelimit-remaining` to be between 16~18) while I'm making a much higher API call rate with another organization in another `Script2` (ensure that it breaks the rate limit threshold), the result was that there were no rate limit errors thrown in executing `Script1`, `x-ratelimit-remaining` and `reservoir` were consistently between 16~18 according to the original setting. This should prove that there should be no anomaly in job execution.

**Comment by jamesliupenn** [comment]
@fahadbraveknight @jamesjjk can you verify the PR that I filed regarding this issue: https://github.com/onfleet/node-onfleet/pull/32

**Comment by jamesliupenn** [comment]
Hi folks, I'm going to go ahead and merge the PR as I was able to reproduce the issue on the current master branch. I'll also be pushing to NPM in the meantime, thanks for the feedback and suggestions!

**Comment by jamesliupenn** [comment]
v1.2.0 is now available on NPM https://www.npmjs.com/package/@onfleet/node-onfleet
