### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by oleh-kolinko** [onfleet/node-onfleet#30]
In readme you have
```
For TypeScript, install the typed definition:

npm install @types/onfleet__node-onfleet
```

Types are outdated and not usable for the current version

**Comment by MichaelEvtushenko** [comment]
I have described all types for request / response to OnFleet API, for e.g.
```
interface OnFleetContainer {
    organization?: string;
    worker?: string;
    team?: string;
    type: OnFleetContainerType;
}

enum OnFleetContainerType {
    ORGANIZATION = 'ORGANIZATION',
    TEAM = 'TEAM',
    WORKER = 'WORKER'
}
```

Do you meed these types? I can make a PR with that types declarations

**Comment by marcobeltempo** [comment]
@oleh-kolinko can you provide examples of some outdated types? 

The typed definitions are defined in the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/onfleet__node-onfleet) package. You should be able to open a PR there with any changes you'd like to make.

**Comment by marcobeltempo** [comment]
@jamesliupenn I opened a PR to add/update the typed definitions. You can find a list of changes in the description https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55000.

I can tag you as a reviewer; otherwise, the changes will be reviewed by a DefinitelyTyped maintainer.

**Comment by jamesliupenn** [comment]
@marcobeltempo we have scheduled this to be reviewed in late August during our next sprint. If we make it in time before the maintainers get to it, I will let you know for us to be added as a reviewer :)

**Comment by jcpmmx** [comment]
Done!
