### ISSUE TITLE
[FREQ] There is no metadata endpoint

### ISSUE THREAD

**Issue by mletynski** [onfleet/node-onfleet#35]
**Is your feature request related to a problem? Please describe.**
There is no metadata endpoint.

**Describe the solution you'd like**
There should be metadata endpoint.

**Comment by jamesliupenn** [comment]
Hi @mletynski, do you mean a specific API endpoint for metadata? Metadata should just be a property on entities like `workers` or `tasks` as described in the API doc: https://docs.onfleet.com/reference#metadata

The current wrapper supports adding metadata on all the entities that support metadata, if that's what you're interested in :)

**Comment by mletynski** [comment]
@jamesliupenn i want to invoke for e.g this API 
`curl -X POST "https://onfleet.com/api/v2/destinations/metadata" `
but i don't see such endpoint in Task resources for node.

**Comment by jamesliupenn** [comment]
@mletynski I see what you mean, let me schedule this into the next updates. You can put in a pull request next time if you are familiar with the library, it's under the `resources` directory :)

**Comment by jamesliupenn** [comment]
@mletynski I've put in the tickets to get this fix in, it should be prioritized sometime in the coming weeks. Thanks for bringing this to our attention!

**Comment by jamesliupenn** [comment]
Sorry for not following up on this, but the `matchMetadata` functions were in versions >1.2.3 back in May https://github.com/onfleet/node-onfleet/pull/39
