### ISSUE TITLE
[FREQ] Creating tasks in batch should be transactional

### ISSUE THREAD

**Issue by mletynski** [onfleet/node-onfleet#36]
**Is your feature request related to a problem? Please describe.**
When creating tasks in batch and there is a validation error for one of them instead of rollbacking whole batch the tasks which were created before validation error task are created.

**Describe the solution you'd like**
Full transactional approach for creating tasks in batch.

**Comment by jcpmmx** [comment]
@mletynski I'm terribly sorry for the delay!

We're not going to pursue this because batch processing short-circuit is the intended API behavior, and changing that is outside the scope of this project.

Thanks!
