### ISSUE TITLE
[BUG] The type of teams in worker creation is string instead string[]

### ISSUE THREAD

**Issue by eriverotupac** [onfleet/node-onfleet#57]
**Describe the bug**
It is about the type of `teams` property in the creation of a worker.

**To Reproduce**
1. yarn add @types/onfleet__node-onfleet --dev
2. Try to create a driver:
```
onfleetApi.workers.create({
        name: 'A Swartz',
        phone: '617-342-8853',
        teams: ['nz1nG1Hpx9EHjQCJsT2VAs~o'],
        vehicle: { type: 'CAR', description: 'Tesla Model 3', licensePlate: 'FKNS9A', color: 'purple' },
      });
```
3. Type 'string[]' is not assignable to type 'string'.
[Workers.d.ts(83, 5): ]()The expected type comes from property 'teams' which is declared here on type 'CreateWorkerProps'

**Expected behavior**
Allow to create driver without type warnings.

**Additional context**
@types/onfleet__node-onfleet": "^1.2.2"

**Comment by YokySantiago** [comment]
This PR will fix the issue once it is approved and merged 
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64019

**Comment by YokySantiago** [comment]
New @types/onfleet__node-onfleet
 version has been release. Please use the version 1.3.2
