### ISSUE TITLE
[BUG] Typing on  Tasks#createBatch is broken

### ISSUE THREAD

**Issue by FPierre** [onfleet/node-onfleet#58]
**Describe the bug**
It is about the type expected in the batch creation of tasks.

**To Reproduce**

1. yarn add -D @types/onfleet__node-onfleet
2. Try to batch create tasks:

```ts
onfleetApi.tasks.batchCreate([
  {
    destination: {
      address: { unparsed: '...' },
    },
    recipients: [
      { name: '...', phone: '...' },
    ],
  },
]);
```

3. Cause the error:

```
...
status: 1000,
cause: "Batch task creation requires that you provide a 'tasks' array property.",
...
```

4. Make the call works:

```ts
// @ts-ignore
onfleetApi.tasks.batchCreate({
  tasks: [
    {
      destination: {
        address: { unparsed: '...' },
      },
      recipients: [
        { name: '...', phone: '...' },
      ],
    },
  ],
});
```

**Expected behavior**
Allow to batch create tasks without error, following [the API documentation](https://docs.onfleet.com/reference#create-tasks-in-batch).

**Additional context**
`@types/onfleet__node-onfleet": "^1.2.2"`

**Comment by daniel-at-mvst** [comment]
I'm facing the same issue!

**Comment by YokySantiago** [comment]
This PR will fix the issue once it is approved and merged 
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64019

**Comment by YokySantiago** [comment]
New @types/onfleet__node-onfleet
 version has been release. Please use the version 1.3.2
