### ISSUE TITLE
[FREQ] Creating a definitely typed package

### ISSUE THREAD

**Issue by marcobeltempo** [onfleet/node-onfleet#7]
Hi @jamesliupenn,

I was wondering if creating a typed definition was in the pipeline?
I've started writing a typed definition library and would love to support this project.

**Comment by jamesliupenn** [comment]
Hi @marcobeltempo, thanks for the opened issues! We do not currently have any ongoing projects in the pipeline regarding our API wrapper libraries, so if you have something in mind, you are more than welcome to contribute/support directly :)

**Comment by jamesliupenn** [comment]
@marcobeltempo Just invited you to become a collaborator to this repository. Feel free to put in PRs anytime and we'll get these enhancements in!

**Comment by marcobeltempo** [comment]
@jamesliupenn quick update

I've contributed a typed definition to the [DefinitelyTyped - @types/onfleet__node-onfleet](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/onfleet__node-onfleet) project.

To include in a typescript project, run the following command:
`npm install --save-dev @types/onfleet__node-onfleet`

The library contains definitions for all resource methods (including props) and response objects.

**Comment by jamesliupenn** [comment]
@marcobeltempo great to know! I'll review it soon and feature the type definition library you created in the repo as well! Thanks again for your contribution!
