### ISSUE TITLE
[BUG] ServiceError returns wrong name

### ISSUE THREAD

**Issue by marcobeltempo** [onfleet/node-onfleet#8]
**Describe the bug**
The `ServiceError` class sets the `name` to `RateLimitError` instead of `ServiceError`.

[/lib/error.js#L45](https://github.com/onfleet/node-onfleet/blob/master/lib/error.js#L45)

Also in the following catch black [/lib/Methods.js#L108](https://github.com/onfleet/node-onfleet/blob/master/lib/Methods.js#L108), you can throw the caught error without calling `new`. This will maintain the error name, making it useful for debugging and testing.

```js
// from
 catch((error) => {
    throw new Error(error);
  });

// to
 catch((error) => {
    throw (error)
  });
```

**Comment by jamesliupenn** [comment]
https://github.com/onfleet/node-onfleet/pull/13

**Comment by jamesliupenn** [comment]
Fixed and included TS types!
