### ISSUE TITLE
[BUG]  the type declaration for tasks.batchCreate is incorrect. 

### ISSUE THREAD

**Issue by murphp15** [onfleet/node-onfleet#85]
**Describe the bug**
In the documentation it says  batchCreate should take in an array
```typescript
declare class Task {
    batchCreate(tasks: Task.CreateTaskProps[]): Promise<Task.OnfleetTask[]>;
```

However this is not correct. It needs an outer "tasks" element for the api to accept it. 

**To Reproduce**
```typescript
// @ts-ignore
const result = await onfleetApi.tasks.batchCreate([array of Task.CreateTaskProps])
// errors from server
```

**To Fix**
```typescript
// @ts-ignore
const result = await onfleetApi.tasks.batchCreate(
                {
                    // @ts-ignore
                    tasks: [array of Task.CreateTaskProps]
                })
```

**Comment by omikader** [comment]
+1, I'm getting this error when I use the signature in `Task.d.ts`

```
"Batch task creation requires that you provide a 'tasks' array property."
```

**Comment by YokySantiago** [comment]
This PR will fix the issue once it is approved and merged 
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64019

**Comment by YokySantiago** [comment]
New @types/onfleet__node-onfleet
 version has been release. Please use the version 1.3.2
