### ISSUE TITLE
[BUG] request timeouts when publishing lots of tasks

### ISSUE THREAD

**Issue by murphp15** [onfleet/node-onfleet#86]
**Describe the bug**
I am publishing a large amount of tasks to my project. 
I get timeout events when using this package.
Below are the errors. 

What is the point in the library if it doesn't handle batching?  
 
```
0|prod nod | erorr  FetchError: network timeout at: https://onfleet.com/api/v2/tasks/batch
0|prod nod |     at Timeout.<anonymous> (/root/DAD/api/node_modules/node-fetch/lib/index.js:1484:13)
0|prod nod |     at listOnTimeout (node:internal/timers:559:17)
0|prod nod |     at processTimers (node:internal/timers:502:7) {
0|prod nod |   type: 'request-timeout'
0|prod nod | }

```

**To Reproduce**
Publish more than 700 tasks in a single request using the this package. 

**Expected behavior**
If batching is needed then it should be handled seamlessly in the library.

**Comment by Threeethan** [comment]
The team is working on the underlying batch endpoint - have a look at the notes on the [api documentation](https://docs.onfleet.com/reference/create-tasks-in-batch) for the caveats on the current situation.

There is some work in progress, and once that is deployed we'll make the appropriate changes to this wrapper. However, I don't think that we'll be able to resolve this via the wrapper itself (without significant alterations to our design scheme) so I'm going to go ahead and close this particular issue.
